=== ToniViz/RepositoryModel/Proyecto.xsd
<?xml version="1.0"?>

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <!-- Simple elements definitions -->
    <xs:element name="descripcion" type="xs:token"/>
    <xs:element name="identificador" type="xs:string"/>
    <xs:element name="idversion" type="xs:float"/>
    <xs:element name="fecha" type="xs:date"/>
    <xs:element name="url" type="uri"/>
    <xs:element name="nombreautor" type="xs:string"/>
    <xs:element name="descargas" type="xs:long"/>
      
    <!-- Attribute definition -->
    
    <xs:attribute name="id" type="xs:ID"/>
        
    <!-- Data types definitions -->
    
    <xs:simpleType name="uri">
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="http://www.*"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tipo">
        <xs:restriction base="xs:normalizedString">
            <xs:enumeration value="eCos_License"/>
            <xs:enumeration value="Eclipse_Public_License"/>
            <xs:enumeration value="Common_Public_License"/>
            <xs:enumeration value="OpenSSL_License"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="idproyecto">
        <xs:list itemType="xs:positiveInteger"/>
    </xs:simpleType>
       
    <!-- Complex elements definitions -->
       
    <xs:element name="nombre">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="identificador"/>
                <xs:element ref="descripcion"/>
            </xs:sequence>
            <xs:attribute ref="id" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="autor">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="identificador"/>
                <xs:element ref="fecha"/>
                <xs:element name="idproyectos" type="idproyecto"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="caracteristicas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="descripcion" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
     <xs:element name="version">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="idversion"/>
                <xs:element ref="url"/>
                <xs:element ref="fecha"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="categoria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="palabras" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="licencia">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="descripcion"/>
            </xs:sequence>
            <xs:attribute name="tipolicencia" type="tipo" use="required"/>
     </xs:complexType>
    </xs:element>
    
    <xs:element name="ficheros">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="url" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
      
        
    <!-- Document definition -->
    
    <xs:element name="proyecto">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre"/>
                <xs:element ref="autor"/>
                <xs:element ref="caracteristicas"/>
                <xs:element ref="version" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="categoria"/>
                <xs:element ref="licencia"/>
                <xs:element ref="ficheros"/>
                <xs:element name="descargas" type="xs:long"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    

</xs:schema>

=== ToniViz/RepositoryModel/proyecto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    XML document validated by XML Schema Proyecto.xsd
    This document models a project repository. It has a project name, author, features, version, category, license and associated files.
    Each element has subelements that describe it.  
-->


<proyecto
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Proyecto.xsd'>
    <nombre id="Project">
        <identificador>Prototipo</identificador>
        <descripcion>Descripcion del proyecto</descripcion>
    </nombre>
    <autor>
        <identificador>Jorge</identificador>
        <fecha>2012-10-23</fecha>
        <idproyectos>10 25 13</idproyectos>
    </autor>
    <caracteristicas>
        <descripcion>Eficiente</descripcion>
        <descripcion>Rapido</descripcion>
        <descripcion>Seguro</descripcion>
    </caracteristicas>
    <version>
        <idversion>01</idversion>
        <url>http://www.angeles.com</url>
        <fecha>2020-07-24</fecha>
    </version>
    <version>
        <idversion>02</idversion>
        <url>http://www.jupiter.es</url>
        <fecha>2021-09-21</fecha>
    </version>
    <categoria>
        <palabras>POO</palabras>
        <palabras>Java</palabras>
        <palabras>PHP</palabras>
    </categoria>
    <licencia tipolicencia="eCos_License">
        <descripcion>Licencia valida para el tipo especificado</descripcion>
    </licencia>
    <ficheros>
        <url>http://www.locos.com</url>
        <url>http://www.archivodos.com</url>
    </ficheros>
    <descargas>1024</descargas>

</proyecto>
